-- Baseline schema for clinic_notifications_db.
-- Uses IF NOT EXISTS so the migration is a no-op on databases that were
-- previously managed by Hibernate ddl-auto (combined with baseline-version 0).

CREATE TABLE IF NOT EXISTS notifications (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        TIMESTAMP(6) NOT NULL,
    updated_at        TIMESTAMP(6) NOT NULL,
    user_id           BIGINT NOT NULL,
    message           TEXT NOT NULL,
    type              VARCHAR(50) NOT NULL,
    read              BOOLEAN NOT NULL,
    related_entity_id BIGINT
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_created ON notifications (user_id, created_at DESC);
