-- Idempotency ledger for consumed RabbitMQ events (at-least-once delivery).

CREATE TABLE IF NOT EXISTS processed_events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    event_id   UUID NOT NULL UNIQUE,
    event_type VARCHAR(100) NOT NULL
);
