-- Baseline schema for clinic_portal.
-- Uses IF NOT EXISTS so the migration is a no-op on databases that were
-- previously managed by Hibernate ddl-auto (combined with baseline-version 0).

CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    email           VARCHAR(255) NOT NULL UNIQUE,
    password_hash   TEXT NOT NULL,
    first_name      VARCHAR(100) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    phone_number    VARCHAR(20),
    role            VARCHAR(20) NOT NULL,
    active          BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS specializations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    name        VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE IF NOT EXISTS rooms (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        TIMESTAMP(6) NOT NULL,
    updated_at        TIMESTAMP(6) NOT NULL,
    room_number       VARCHAR(10) NOT NULL UNIQUE,
    floor             INTEGER NOT NULL,
    type              VARCHAR(20) NOT NULL,
    status            VARCHAR(20) NOT NULL,
    specialization_id BIGINT REFERENCES specializations (id)
);

CREATE TABLE IF NOT EXISTS patient_profiles (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at              TIMESTAMP(6) NOT NULL,
    updated_at              TIMESTAMP(6) NOT NULL,
    user_id                 BIGINT NOT NULL UNIQUE REFERENCES users (id),
    date_of_birth           DATE,
    gender                  VARCHAR(20),
    blood_type              VARCHAR(20),
    address                 TEXT,
    emergency_contact_name  VARCHAR(150),
    emergency_contact_phone VARCHAR(20),
    height_cm               INTEGER,
    weight_kg               NUMERIC(5, 2),
    allergies               TEXT,
    chronic_conditions      TEXT,
    family_history          TEXT,
    lifestyle_smoking       VARCHAR(40),
    lifestyle_alcohol       VARCHAR(40),
    lifestyle_exercise      VARCHAR(40),
    lifestyle_diet          VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS doctor_profiles (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       TIMESTAMP(6) NOT NULL,
    updated_at       TIMESTAMP(6) NOT NULL,
    user_id          BIGINT NOT NULL UNIQUE REFERENCES users (id),
    license_number   VARCHAR(100) NOT NULL UNIQUE,
    biography        TEXT,
    consultation_fee NUMERIC(10, 2),
    rating           NUMERIC(3, 1),
    room_id          BIGINT UNIQUE REFERENCES rooms (id)
);

CREATE TABLE IF NOT EXISTS doctor_specializations (
    doctor_id         BIGINT NOT NULL REFERENCES doctor_profiles (id),
    specialization_id BIGINT NOT NULL REFERENCES specializations (id)
);

CREATE TABLE IF NOT EXISTS appointments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       TIMESTAMP(6) NOT NULL,
    updated_at       TIMESTAMP(6) NOT NULL,
    patient_id       BIGINT NOT NULL REFERENCES patient_profiles (id),
    doctor_id        BIGINT NOT NULL REFERENCES doctor_profiles (id),
    scheduled_at     TIMESTAMP(6) NOT NULL,
    duration_minutes INTEGER NOT NULL,
    status           VARCHAR(20) NOT NULL,
    mode             VARCHAR(20) NOT NULL,
    reason           TEXT,
    started_at       TIMESTAMP(6),
    completed_at     TIMESTAMP(6),
    rating           INTEGER,
    review           TEXT
);

CREATE TABLE IF NOT EXISTS consultation_notes (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMP(6) NOT NULL,
    updated_at     TIMESTAMP(6) NOT NULL,
    appointment_id BIGINT NOT NULL UNIQUE REFERENCES appointments (id),
    diagnosis      TEXT,
    treatment      TEXT,
    prescription   TEXT,
    notes          TEXT
);

CREATE TABLE IF NOT EXISTS medical_documents (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at           TIMESTAMP(6) NOT NULL,
    updated_at           TIMESTAMP(6) NOT NULL,
    consultation_note_id BIGINT NOT NULL REFERENCES consultation_notes (id),
    original_file_name   VARCHAR(255) NOT NULL,
    content_type         VARCHAR(100) NOT NULL,
    storage_path         TEXT NOT NULL,
    file_size_bytes      BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_appointments_doctor_scheduled ON appointments (doctor_id, scheduled_at);
CREATE INDEX IF NOT EXISTS idx_appointments_patient ON appointments (patient_id);
CREATE INDEX IF NOT EXISTS idx_appointments_status ON appointments (status);
