-- Transactional outbox table (Outbox pattern).

CREATE TABLE IF NOT EXISTS outbox_events (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMP(6) NOT NULL,
    updated_at     TIMESTAMP(6) NOT NULL,
    event_id       UUID NOT NULL UNIQUE,
    event_type     VARCHAR(100) NOT NULL,
    queue          VARCHAR(200) NOT NULL,
    payload        TEXT NOT NULL,
    correlation_id VARCHAR(64),
    published_at   TIMESTAMP(6)
);

-- Partial index: the relay only ever scans unpublished rows.
CREATE INDEX IF NOT EXISTS idx_outbox_unpublished ON outbox_events (id) WHERE published_at IS NULL;
