-- Recurring weekly working hours per doctor.

CREATE TABLE IF NOT EXISTS doctor_availability (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    doctor_id   BIGINT NOT NULL REFERENCES doctor_profiles (id),
    day_of_week VARCHAR(10) NOT NULL,
    start_time  TIME(6) NOT NULL,
    end_time    TIME(6) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_availability_doctor ON doctor_availability (doctor_id);
